### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by realkris** [WuyangLuo/SPMPGAN#1]
Thanks for you work.

I was trying to reproduce your work but stucked at data preparations, I read your paper in every corner but still cannot get idea how to process the dataset. would you share your script or describe in detail how the data was generated?

Also would you also your environment so we do not need to guess a lot.

**Comment by WuyangLuo** [comment]
You can find data preprocessing in Section 4.1

Specifically，
for cityscapes dataset:
1. Resize all images to 512 * 256
2. Randomly crop 256*256 patches

for other datasets：
1.  Resize all the images with their longer sides no more than 384 and their shorter sides no less than 256
2. Randomly crop 256*256 patches

**Comment by WuyangLuo** [comment]
experiment environment: pytorch 1.10, python 3.7
